### ISSUE TITLE
Lazify objects can't be json_encode'd

### ISSUE THREAD

**Issue by trubesv** [numberly/flask-stupe#15]

**Comment by ramnes** [comment]
Whut?

Do you have a test case?

**Comment by ramnes** [comment]
This is an issue related to Lazify and Flask, not Flask-Stupe. See https://github.com/numberly/lazify/issues/4.

That being said, Flask-Stupe makes it easy to work around this problem:
```python
app.json_encoder.add_rule(LazyProxy, lambda p: p.value)
```
