### ISSUE TITLE
Avoid prettifying json

### ISSUE THREAD

**Issue by guilbep** [numberly/flask-stupe#16]
As we can see here:  http://flask.pocoo.org/docs/0.12/api/

Today flask prettify the json output unless:

This function’s response will be pretty printed if it was not requested with X-Requested-With: XMLHttpRequest to simplify debugging unless the JSONIFY_PRETTYPRINT_REGULAR config parameter is set to false. Compressed (not pretty) formatting currently means no indents and no spaces after separators.

We don't want to pass that http header each time!

**Comment by ramnes** [comment]
See https://github.com/numberly/flask-stupe/pull/10
