### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by itsjef** [numberly/flask-stupe#21]
I ran the example in README.md and caught this error while POST-ing data to `/user` endpoint with the payload:

```json
{
  "username": "itsjef",
  "password": "itsme"
}
```

It was this line: https://github.com/numberly/flask-stupe/blob/master/flask_stupe/validation.py#L19 that caused the bug, since `schema.load()` was an instance method.

My workaround is to replace

```python
@schema_required(UserSchema)
```

with

```python
@schema_required(UserSchema())
```

Additional Info:
- python version: **3.6.5**
- flask-stupe version: **3.6.4**
- pymongo: **3.7.1**
- marshmallow: **2.15.4**

**Comment by rambobinator** [comment]
Hi, thanks for pointing this out !

I'm not sure of what should be fixed here: code or documentation.
Personally i'd like to allow both schema class and instance to be passed as parameter (i think it's how marshmallow behaves). @ramnes @trubesv any thoughts ?

**Comment by ramnes** [comment]
Let's start by fixing the README.

@rambobinator I've seen the branch you've made, please rename it and open a MR so that we discuss can if we want this or not.

Thank you @itsjef!
